languages = {
  "af": "Afrikaans",
  "ar": "العربية",
  "az": "Azərbaycan dili",
  "be": "Беларуская",
  "bg": "Български",
  "bn": "বাংলা",
  "bs": "Bosanski",
  "ca": "Català",
  "cs": "Čeština",
  "cy": "Cymraeg",
  "da": "Dansk",
  "de": "Deutsch",
  "el": "Ελληνικά",
  "en": "English",
  "es": "Español",
  "et": "Eesti",
  "eu": "Euskara",
  "fa": "فارسی",
  "fi": "Suomi",
  "fr": "Français",
  "ga": "Gaeilge",
  "gl": "Galego",
  "gu": "ગુજરાતી",
  "he": "עברית",
  "hi": "हिन्दी",
  "hr": "Hrvatski",
  "hu": "Magyar",
  "hy": "Հայերեն",
  "id": "Bahasa Indonesia",
  "is": "Íslenska",
  "it": "Italiano",
  "ja": "日本語",
  "ka": "ქართული",
  "kk": "Қазақ тілі",
  "kn": "ಕನ್ನಡ",
  "ko": "한국어",
  "ku": "كوردى",
  "lt": "Lietuvių",
  "lv": "Latviešu",
  "ml": "മലയാളം",
  "mk": "Македонски",
  "ms": "Bahasa Melayu",
  "mt": "Malti",
  "nl": "Nederlands",
  "no": "Norsk",
  "pa": "ਪੰਜਾਬੀ",
  "pl": "Polski",
  "pt": "Português",
  "ro": "Română",
  "ru": "Русский",
  "sk": "Slovenčina",
  "sl": "Slovenščina",
  "sq": "Shqip",
  "sr": "Српски",
  "sv": "Svenska",
  "sw": "Kiswahili",
  "ta": "தமிழ்",
  "te": "తెలుగు",
  "th": "ไทย",
  "tr": "Türkçe",
  "uk": "Українська",
  "ur": "اردو",
  "vi": "Tiếng Việt",
  "zh": "中文 (Zhōngwén)",
  "zu": "isiZulu"
}
